spring.application.name=EmployeePayrollApp
# MySQL Configuration
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/payroll_service
spring.datasource.username=root
spring.datasource.password=bridgelabz99

# Hibernate (Optional for future use)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
